version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/tantei/server
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: root